"use client"

import { useEffect } from "react"

export default function Head() {

  useEffect(() => {
    let docTitle = document.title

    window.addEventListener('blur', () => {
      document.title = 'Come back ;('
    })
  
    window.addEventListener('focus', () => {
      document.title = docTitle
    }) 
  }, [])

  

  return (
    <>
      <title>Hey there ;)</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
